### ISSUE TITLE
Map BAL wrappers

### ISSUE THREAD

**Issue by viniabussafi** [balancer-labs/dune-spellbook#108]

**Comment by mendesfabio** [comment]
https://dune.com/Marcov/liquid-vecrv

**Comment by viniabussafi** [comment]
Refs:
https://dune.com/queries/3396534/5699908
https://dune.com/queries/3368180/5650343

**Comment by viniabussafi** [comment]
repurposing the deprecated LBPs dashboard: https://dune.com/balancer/vebal-wrappers

**Comment by viniabussafi** [comment]
Dashboard is mainly done/formatted. waiting for feedback

**Comment by viniabussafi** [comment]
reduced noise and filtered outliers
