### ISSUE TITLE
Map vlAURA holders

### ISSUE THREAD

**Issue by viniabussafi** [balancer-labs/dune-spellbook#129]

**Comment by viniabussafi** [comment]
map vlaura vs. vebal rounds

**Comment by viniabussafi** [comment]
ref: 
https://etherscan.io/address/0x3fa73f1e5d8a792c80f426fc8f84fbf7ce9bbcac
https://vscode.blockscan.com/ethereum/0x3fa73f1e5d8a792c80f426fc8f84fbf7ce9bbcac
https://dune.com/queries/3999509

**Comment by viniabussafi** [comment]
vlAURA rounds: https://dune.com/queries/4001808. same results as dune.asnogordo.result_aura_lock_period
veBAL rounds: https://dune.com/queries/4001811

**Comment by viniabussafi** [comment]
Update:
this [query](https://dune.com/queries/4004772) works for latest data, but [this](https://dune.com/queries/3999509?category=decoded_project&namespace=aura_finance&contract=AuraLocker&blockchains=ethereum&id=aura_finance_ethereum.AuraLocker_evt_Staked) one still needs to be fixed for historical data regarding unlockable vlaura

**Comment by viniabussafi** [comment]
will work with current balances, as we want a pie chart of vlaura distribution, but after thar will go back to the challenge of rebuilding the data historically

**Comment by viniabussafi** [comment]
![image](https://github.com/user-attachments/assets/ffd9f28f-1b1e-4a4f-b58b-5c69bea52731)
getting close 🙏

**Comment by viniabussafi** [comment]
Balances by address for debugging: https://dune.com/queries/4008271

**Comment by viniabussafi** [comment]
Results match with this function for current balances: https://etherscan.io/address/0x3fa73f1e5d8a792c80f426fc8f84fbf7ce9bbcac#readContract#F24

**Comment by viniabussafi** [comment]
Current veBAL Balances (vlAURA holders breakdown): https://dune.com/queries/4008624/6748633?category=asset-tracking

**Comment by viniabussafi** [comment]
Update:
working on vlaura balances by round here: https://dune.com/queries/4005633
last step is properly calculating vebal balances and voting power

**Comment by mendesfabio** [comment]
this is the 1st user I tried to play with `0x01a0f8f364c2fec07cfcdebd2980da3f950d0410` and I noticed that:

- Gaps between vlAURA rounds need to be filled;
- Dune returns `4197.7687402245365` for vlAURA 115 while Etherscan returns 0.

**Comment by viniabussafi** [comment]
[historical vlAURA balances by voting round and provider](https://dune.com/queries/4022098)

**Comment by viniabussafi** [comment]
[historical vlAURA balances by voting round and address](https://dune.com/queries/4005633)

**Comment by viniabussafi** [comment]
[vlAURA balances by voting round and delegate](https://dune.com/queries/4023009)

**Comment by viniabussafi** [comment]
Joining everything in [vlaura_balances_round](https://dune.com/queries/4023187). The idea is to materialize this query once credits refresh and then be able to get data by
- address
- provider
- delegate

**Comment by viniabussafi** [comment]
[Current vlAURA Distribution per provider](https://dune.com/queries/4024379)
[Current vlAURA Distribution per delegate](https://dune.com/queries/4024403)
[Current veBAL balances (vlAURA delegates breakdown)](https://dune.com/queries/4024424)

**Comment by viniabussafi** [comment]
Ok, seems we've definitely progressed. Organizing the multiple links I sent here:
Main query, to be materialized once credits refresh, containing vlAURA and veBAL balances for each holder, including 'provider' for labelling and 'delegate': [vlaura_balances_round](https://dune.com/queries/4023187)

Current vlAURA distributions:
[Current vlAURA Distribution per provider](https://dune.com/queries/4024379)
[Current vlAURA Distribution per delegate](https://dune.com/queries/4024403)
[Current vlAURA Distribution per address
](https://dune.com/queries/4025328)

Current veBAL balances
[Current veBAL balances (vlAURA delegates breakdown)](https://dune.com/queries/4024424)
[Current veBAL balances (vlAURA providers breakdown)](https://dune.com/queries/4025331)
[Current veBAL balances (vlAURA addresses breakdown)](https://dune.com/queries/4025336)

**Comment by viniabussafi** [comment]
[Historical veBAL balances (vlAURA providers breakdown)](https://dune.com/queries/4025600)

**Comment by viniabussafi** [comment]
[historical vlAURA balances by voting round and address](https://dune.com/queries/4005633/6776717)
[historical vlAURA balances by voting round and provider
](https://dune.com/queries/4025662)
[historical vlAURA balances by voting round and delegate](https://dune.com/queries/4025664)

**Comment by viniabussafi** [comment]
Added to veBAL dashboard
![image](https://github.com/user-attachments/assets/6baadf2d-70b3-451c-ba09-3020adf20a65)

**Comment by viniabussafi** [comment]
done, added to dashboard and sent to team
