### ISSUE TITLE
Fix Balancer on Fraxtal snapshots upload

### ISSUE THREAD

**Issue by viniabussafi** [balancer-labs/dune-spellbook#136]
May need some help on this one, @mendesfabio. 
As you can see [here](https://dune.com/balancer/balancer-on-fraxtal), data for liquidity is way off and volume doesn't seem to be accurate as well.
Weird enough that it's working well for Mode, which uses the same script

**Comment by mendesfabio** [comment]
I've already deployed a hotfix to the Subgraph, have to wait a few hours to check the results

**Comment by viniabussafi** [comment]
Fixed
