### ISSUE TITLE
fix vault buffers queries

### ISSUE THREAD

**Issue by mendesfabio** [balancer-labs/dune-spellbook#168]
TLDR track `Unwrap` and `Wrap` events - look at this [transaction](https://sepolia.etherscan.io/tx/0x060e26ff1ee57c17a74b68fa6629bdb2e5eff68ad40996623a47732d01931d21#eventlog) for example

**Comment by mendesfabio** [comment]
@viniabussafi

**Comment by viniabussafi** [comment]
WIP [here](https://dune.com/queries/4144874) - shares match but balances don't

**Comment by viniabussafi** [comment]
Status: SC team will introduce new fields to events for balances and flagging rebalancing operations

**Comment by viniabussafi** [comment]
[query](https://dune.com/queries/4144874) fixed
