### ISSUE TITLE
Analyse percentage of BPT staked

### ISSUE THREAD

**Issue by viniabussafi** [balancer-labs/dune-spellbook#78]
A request came up from the maxis in order to check what's the % of BPTs staked per pool on mainnet and, in turn, to what % of our TVL it amounts to.

 - [Analysis per pool](https://dune.com/queries/3660271/6155565?Blockchain_e15077=ethereum&Pool+Address_t6c1ea=0x596192bB6e41802428Ac943D2f1476C1Af25CC0E)
 - [Analysis per chain](https://dune.com/queries/3684247/6196994)

**Comment by viniabussafi** [comment]
[Current snapshot](https://dune.com/queries/3685020/6198141)

**Comment by mendesfabio** [comment]
- [missing data 1](https://dune.com/queries/3690031)
- [missing data 2](https://dune.com/queries/3690034)

**Comment by viniabussafi** [comment]
Analysing the [outliers](https://dune.com/queries/3689794) (results where the number of BPTs staked > BPT supply), me and Fábio identified an error on the bpt_supply spell, which was addressed on this [PR](https://github.com/duneanalytics/spellbook/pull/5872).

Previous code:

```
` 
   joins_and_exits AS (
        SELECT 
            j.block_date, 
            j.tokenOut AS bpt, 
            SUM(COALESCE(ajoins, 0) - COALESCE(aexits, 0)) OVER (PARTITION BY j.tokenOut ORDER BY j.block_date ASC) AS adelta
        FROM joins j
        FULL OUTER JOIN exits e ON j.block_date = e.block_date AND e.tokenIn = j.tokenOut
    ),
```

Now:
```
   joins_and_exits_1 AS (
        SELECT 
            *
        FROM joins 
        
        UNION ALL
        
        SELECT 
            *
        FROM exits
            ),

    joins_and_exits AS (
        SELECT 
            block_date, 
            token AS bpt, 
            LEAD(block_date, 1, NOW()) OVER (PARTITION BY token ORDER BY block_date) AS day_of_next_change,
            SUM(amount) OVER (PARTITION BY token ORDER BY block_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS adelta
        FROM joins_and_exits_1
    ),
```
