### ISSUE TITLE
add protocol fee spell to fantom

### ISSUE THREAD

**Issue by mendesfabio** [balancer-labs/dune-spellbook#85]
ProtocolFeeCollector: https://ftmscan.com/address/0xc6920d3a369e7c8bd1a22dbe385e11d1f7af948f

**Comment by mendesfabio** [comment]
this [dashboard](https://lookerstudio.google.com/u/0/reporting/ce0e46c4-fd56-4512-beca-3cb6ffd24b11/page/p_tgix1qe55c) is helpful for cross-checking. it seems a bunch of fees are collected in BPTs so we need their prices as well to have accurate numbers.

**Comment by viniabussafi** [comment]
Working on a [PR](https://github.com/duneanalytics/spellbook/pull/5961)

**Comment by viniabussafi** [comment]
Initial tests passed, but still a long way to go (about 5x) on fees collected, probably due to missing tokens on prices.usd. Will work on it.

**Comment by viniabussafi** [comment]
Turns out it is due to missing pool factories, for which franz has created a [PR](https://github.com/duneanalytics/spellbook/pull/5964). WIll proceed with my PR and once Franz' one gets merged, results should be as expected.

**Comment by viniabussafi** [comment]
ready to merge

**Comment by viniabussafi** [comment]
PR merged - need to validate data, will wait for one more run of the spell tonight

**Comment by viniabussafi** [comment]
Both mine and franz' pr were merged, spells ran today and numbers look good
